name: Build and Upload Wheels

on:
  push:
    tags:
      - 'v*'  # e.g. v0.1.0

jobs:
  build:
    name: Build Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install maturin
        run: pip install maturin

      # --- Install cfitsio ---
      - name: Install cfitsio on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libcfitsio-dev

      - name: Install cfitsio on macOS
        if: runner.os == 'macOS'
        run: brew install cfitsio

      - name: Build wheel with maturin
        run: maturin build --release --strip -o dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl

  upload:
    name: Upload to GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Gather all wheels
        run: |
          mkdir wheels
          find dist -name '*.whl' -exec cp {} wheels/ \;

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: wheels/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
